data_file: ./data/topic_constraints_en_2403_v2.json
api_configs_file: ./configs/api_configs.yml
save_root: ./results/res_2410
llm: gemma2
# stages: ['query']
stages: ['evaluate']

#### query stage ####
query_template_file: ./templates/base.txt
# query_template_file: ./templates/softmoe.txt
num_constraints: 2
reset_progress: False
first_k: 2

#### evaluate params ####
# result_file: 
multi_type_agg: max
