llm_type: gpt4
template: analysis_template
data_path: ./data/topic_constraints_en_2403_v2.json
save_path: ./results/res_240815

gpt3:
  api_key: xxx
  role: user
  model: gpt-3.5-turbo

gpt4:
  api_key: xxx
  role: user
  model: gpt-4-1106-preview

vicuna:
  api_key: EMPTY
  base_url: http://localhost:9009/v1/
  role: user
  model: vicuna-13b-v1.5

constraint:
  types: ['s=l-i=l-e=l-40',
          's=h-i=l-e=l-20',
          's=l-i=h-e=l-20',
          's=l-i=l-e=h-20',]
  seed: 0