run:
  llm_type: vicuna
  ref_llm_type: gpt4
  # save_path: ./outputs/vicuna/evals
  # save_path: ./outputs/gpt3/evals

# resp_path: ./gpt3_types=skill_seed=0.json
resp_path: ./results/vicuna_types=item_seed=0.json
ref_resp_path: ./results/gpt4_types=item_seed=0.json

gpt4:
  api_key: xxx
  role: user
  model: gpt-4-1106-preview

constrains:
  types: ['item']
  seed: 0