run:
  openai:
    engine: 'gpt-3.5-turbo'
    role: 'assistant'
  save_dir: './output/gpt_query_trial'
  credential_file: './configs/credentials.yml'
  seed: 0
  n_item: 50
  save_name: gpt_prompt_plain0_3cons1_s0

data:
  item_file: ./Dataset/topic_constrains.csv

prompt:
  template_file: ./configs/prompts/gpt_template.yml
  type: PLAIN
  choice: 0
  n_constrain: 3
  constrain_choice: 2
  seed: 0
  